In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf
from pandas_datareader import data as pdr

a = yf.Ticker('AA')

In [4]:
dir(a)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_balancesheet',
 '_base_url',
 '_calendar',
 '_cashflow',
 '_download_options',
 '_earnings',
 '_expirations',
 '_financials',
 '_fundamentals',
 '_get_fundamentals',
 '_history',
 '_info',
 '_institutional_holders',
 '_isin',
 '_major_holders',
 '_mutualfund_holders',
 '_options2df',
 '_recommendations',
 '_scrape_url',
 '_sustainability',
 'actions',
 'balance_sheet',
 'balancesheet',
 'calendar',
 'cashflow',
 'dividends',
 'earnings',
 'financials',
 'get_actions',
 'get_balance_sheet',
 'get_balancesheet',
 'get_calendar',
 'get_cashflow',
 'get_dividends',
 'get_earnings',
 'get_financials',
 'get_info',
 'get_institutional_holders',
 'get_isin',
 'get_major_holders',
 'get_mutualfund_holders',
 'get_recommendations',
 'get_splits',
 'get_sustainability',
 'history',
 'info',
 'institutional_holders',
 'isin',
 'major_holders',
 'mutualfund_holders',
 'option_chain',
 'options',
 'quarterly_balance_sheet',
 'quarterly_balancesheet',
 'quarterly_cashflow',
 'quarterly_earnings',
 'quarterly_financials',
 'recommendations',
 'splits',
 'sustainability',
 'ticker']

In [16]:
tickers = ['AAPL', 'FB', 'AMZN']
stocks = yf.download(tickers, start = '2015-01-01', end = '2019-12-30')
stocks

[*********************100%***********************]  3 of 3 completed

            Adj Close                               Close               \
                 AAPL         AMZN          FB       AAPL         AMZN
Date
2014-12-31  25.137676   310.350006   78.019997  27.594999   310.350006
2015-01-02  24.898552   308.519989   78.449997  27.332500   308.519989
2015-01-05  24.197117   302.190002   77.190002  26.562500   302.190002
2015-01-06  24.199400   295.290009   76.150002  26.565001   295.290009
2015-01-07  24.538729   298.420013   76.150002  26.937500   298.420013
...               ...          ...         ...        ...          ...
2019-12-20  69.261856  1786.500000  206.300003  69.860001  1786.500000
2019-12-23  70.392090  1793.000000  206.179993  71.000000  1793.000000
2019-12-24  70.459007  1789.209961  205.119995  71.067497  1789.209961
2019-12-26  71.856941  1868.770020  207.789993  72.477501  1868.770020
2019-12-27  71.829674  1869.800049  208.100006  72.449997  1869.800049

                             High                                 Low  \
                    FB       AAPL         AMZN          FB       AAPL
Date
2014-12-31   78.019997  28.282499   312.980011   79.800003  27.552500
2015-01-02   78.449997  27.860001   314.750000   78.930000  26.837500
2015-01-05   77.190002  27.162500   308.380005   79.250000  26.352501
2015-01-06   76.150002  26.857500   303.000000   77.589996  26.157499
2015-01-07   76.150002  27.049999   301.279999   77.360001  26.674999
...                ...        ...          ...         ...        ...
2019-12-20  206.300003  70.662498  1802.969971  207.710007  69.639999
2019-12-23  206.179993  71.062500  1793.000000  208.589996  70.092499
2019-12-24  205.119995  71.222504  1795.569946  206.789993  70.730003
2019-12-26  207.789993  72.495003  1870.459961  207.820007  71.175003
2019-12-27  208.100006  73.492500  1901.400024  208.929993  72.029999

                                          Open                           \
                   AMZN          FB       AAPL         AMZN          FB
Date
2014-12-31   310.010010   77.860001  28.205000   311.549988   79.540001
2015-01-02   306.959991   77.699997  27.847500   312.579987   78.580002
2015-01-05   300.850006   76.860001  27.072500   307.010010   77.980003
2015-01-06   292.380005   75.360001  26.635000   302.239990   77.230003
2015-01-07   295.329987   75.820000  26.799999   297.500000   76.760002
...                 ...         ...        ...          ...         ...
2019-12-20  1782.449951  203.429993  70.557503  1799.619995  207.479996
2019-12-23  1784.510010  205.679993  70.132500  1788.260010  206.699997
2019-12-24  1787.579956  205.000000  71.172501  1793.810059  206.300003
2019-12-26  1799.500000  205.309998  71.205002  1801.010010  205.570007
2019-12-27  1866.010010  206.589996  72.779999  1882.920044  208.669998

               Volume
                 AAPL     AMZN        FB
Date
2014-12-31  165613600  2048000  19935400
2015-01-02  212818400  2783200  18177500
2015-01-05  257142000  2774200  26452200
2015-01-06  263188400  3519000  27399300
2015-01-07  160423600  2640300  22045300
...               ...      ...       ...
2019-12-20  275978000  5150800  27306900
2019-12-23   98572000  2136400  13348900
2019-12-24   48478800   881300   6046300
2019-12-26   93121200  6005400   9350700
2019-12-27  146266000  6186600  10284200

[1257 rows x 18 columns]

In [14]:
yf.pdr_override()
stock = input("Enter a stock ticker symbol: ")
print(stock)

Enter a stock ticker symbol: QQQ
QQQ

In [15]:
startyear = 2019
startmonth = 1
startday = 2

start = dt.datetime(startyear, startmonth, startday)
now=dt.datetime.now()

df = pdr.get_data_yahoo(stock, start, now)

[*********************100%***********************]  1 of 1 completed

In [58]:
ma = 50 # moving average

smaString = 'Sma_' + str(ma) # simple moving average

df[smaString] = df.iloc[:, 4].rolling(window = ma).mean() # window means the size of the moving window and rolling is for rolling window calculations and 4 because moving average calculated using Adj Close

,Open,High,Low,Close,Adj Close,Volume,Sma_50
Date,,,,,,,
2019-12-30,213.500000,213.630005,211.160004,212.210007,211.008652,21815500,NaN
2019-12-31,211.529999,212.759995,211.199997,212.610001,211.406387,18170900,NaN
2020-01-02,214.399994,216.160004,213.979996,216.160004,214.936295,30969400,NaN
2020-01-03,213.300003,215.470001,213.279999,214.179993,212.967499,27518900,NaN
2020-01-06,212.500000,215.589996,212.240005,215.559998,214.339691,21655300,NaN
...,...,...,...,...,...,...,...
2021-01-26,328.850006,329.760010,327.220001,328.589996,328.589996,25498100,307.075853
2021-01-27,326.260010,326.269989,317.359985,319.429993,319.429993,55264000,307.706889
2021-01-28,320.670013,326.420013,320.029999,321.320007,321.320007,42836300,308.325217
2021-01-29,319.579987,320.720001,312.760010,314.559998,314.559998,55164200,308.763026
2021-02-01,318.109985,321.119995,316.019989,321.010010,321.010010,14872647,309.348403

In [57]:
df = df.iloc[ma:]
df

,Open,High,Low,Close,Adj Close,Volume,Sma_50
Date,,,,,,,
2019-12-30,213.500000,213.630005,211.160004,212.210007,211.008652,21815500,201.323338
2019-12-31,211.529999,212.759995,211.199997,212.610001,211.406387,18170900,201.747616
2020-01-02,214.399994,216.160004,213.979996,216.160004,214.936295,30969400,202.208758
2020-01-03,213.300003,215.470001,213.279999,214.179993,212.967499,27518900,202.661084
2020-01-06,212.500000,215.589996,212.240005,215.559998,214.339691,21655300,203.133511
...,...,...,...,...,...,...,...
2021-01-26,328.850006,329.760010,327.220001,328.589996,328.589996,25498100,307.075853
2021-01-27,326.260010,326.269989,317.359985,319.429993,319.429993,55264000,307.706889
2021-01-28,320.670013,326.420013,320.029999,321.320007,321.320007,42836300,308.325217
2021-01-29,319.579987,320.720001,312.760010,314.559998,314.559998,55164200,308.763026
2021-02-01,318.109985,321.119995,316.019989,321.010010,321.010010,14872647,309.348403

In [59]:
numH = 0
numC = 0

for i in df.index:
    #print(df[smaString][i]) # print(df.iloc[:, 4][i])
    if (df['Adj Close'][i] > df[smaString][i]):
        print("The close is higher.")
        numH += 1
    else:
        print("The close is lower.")
        numC += 1
    
print("Close was higher " + str(numH) + " times.")
print("Close was lower " + str(numC) + " times.")

The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is lower.
The close is higher.
The close is higher.
The close is higher.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is lower.
The close is higher.
The close is lower.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is lower.
The close is higher.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is lower.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
The close is higher.
Close was higher 187 times.
Close was lower 88 times.